### ISSUE TITLE
Weird decimal numbers

### ISSUE THREAD

**Issue by 7RST1** [openinframap/web#4] opened 2019-02-21 11:26 UTC
The value of MW is 0.28.

![skjermbilde fra 2019-02-21 12-20-16](https://user-images.githubusercontent.com/16783057/53165712-aee31500-35d3-11e9-94c3-50d6733fec75.png)

**Comment by russss** [comment] 2019-03-18 14:37
This is a duplicate of openinframap/styles#34 and it is a very weird bug.

**Closed as completed by russss** 2019-03-18 14:37 UTC
