### ISSUE TITLE
Substations on pole aren't displayed

### ISSUE THREAD

**Issue by pyrog** [openinframap/web#9] opened 2019-03-01 03:54 UTC
tag|value
-- | --
name | En Bizerand
operator|Enedis
power|pole
source|Enedis - 06/2018
transformer|distribution
voltage|20000;400

[Example<br/>
<img width="348" alt="capture d ecran 2019-03-01 a 04 50 42" src="https://user-images.githubusercontent.com/2158081/53615318-a4310d00-3bdd-11e9-928d-f0f6de921c16.png">](https://openinframap.org/#17.28/46.451354/5.604929)

**Comment by flacombe** [comment] 2019-03-03 12:08
This is a duplicate of https://github.com/openinframap/styles/issues/29

In medium-term future, all transformer=distribution on poles nodes may get a substation=minor_distribution also.
Stay tuned

**Comment by russss** [comment] 2019-03-18 14:35
Sorry I wasn't being notified about issues on this repo! 

Yeah, we're tracking style issues in the styles repo. Thanks for the report.

**Closed as completed by russss** 2019-03-18 14:35 UTC
