### ISSUE TITLE
OSM ID link uses incorrect type

### ISSUE THREAD

**Issue by rivermont** [openinframap/web#14] opened 2019-03-27 21:42 UTC
I love that there's now a link to the OSM page for features, however it seems to default to `osm.org/way/...`, even on nodes (and possibly relations). It gets the correct ID but just needs to send nodes to `osm.org/node/...` instead.

**Comment by russss** [comment] 2019-03-28 10:55
This is a duplicate of #6 which I forgot to reopen.

**Closed as completed by russss** 2019-03-28 10:55 UTC
